"""restructurer Plan (prix mensuel/annuel, acces par fonctionnalite) et ajouter cycle_facturation sur Abonnement

Revision ID: 0513c3e2bc26
Revises: d139ca69343f
Create Date: 2026-07-25 17:40:38.124762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0513c3e2bc26'
down_revision: Union[str, Sequence[str], None] = 'd139ca69343f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonnements', sa.Column('cycle_facturation', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('prix_mensuel', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('plans', sa.Column('prix_annuel', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('plans', sa.Column('acces_dettes', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('acces_epargne', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('acces_recurrentes', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('acces_templates', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('acces_analyse', sa.Boolean(), nullable=False))
    op.alter_column('plans', 'acces_jarvis',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('plans', 'acces_rapport',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('plans', 'prix')
    op.drop_column('plans', 'acces_prediction')
    op.drop_column('plans', 'max_comptes')
    op.drop_column('plans', 'max_transactions')
    # ### end Alembic commands ###

    # Seed du catalogue des 3 plans — table vide avant cette migration,
    # pas de risque d'écraser des données existantes.
    plans_table = sa.table(
        "plans",
        sa.column("nom", sa.String),
        sa.column("prix_mensuel", sa.Numeric),
        sa.column("prix_annuel", sa.Numeric),
        sa.column("devise", sa.String),
        sa.column("acces_dettes", sa.Boolean),
        sa.column("acces_epargne", sa.Boolean),
        sa.column("acces_recurrentes", sa.Boolean),
        sa.column("acces_templates", sa.Boolean),
        sa.column("acces_analyse", sa.Boolean),
        sa.column("acces_jarvis", sa.Boolean),
        sa.column("acces_rapport", sa.Boolean),
    )
    op.bulk_insert(
        plans_table,
        [
            {
                "nom": "GRATUIT", "prix_mensuel": 0, "prix_annuel": 0, "devise": "XAF",
                "acces_dettes": False, "acces_epargne": False, "acces_recurrentes": False,
                "acces_templates": False, "acces_analyse": False, "acces_jarvis": False, "acces_rapport": False,
            },
            {
                "nom": "ESSENTIEL", "prix_mensuel": 1000, "prix_annuel": 10000, "devise": "XAF",
                "acces_dettes": True, "acces_epargne": True, "acces_recurrentes": True,
                "acces_templates": True, "acces_analyse": False, "acces_jarvis": False, "acces_rapport": False,
            },
            {
                "nom": "PREMIUM", "prix_mensuel": 2500, "prix_annuel": 25000, "devise": "XAF",
                "acces_dettes": True, "acces_epargne": True, "acces_recurrentes": True,
                "acces_templates": True, "acces_analyse": True, "acces_jarvis": True, "acces_rapport": False,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM plans WHERE nom IN ('GRATUIT', 'ESSENTIEL', 'PREMIUM')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('max_transactions', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('max_comptes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('acces_prediction', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('prix', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.alter_column('plans', 'acces_rapport',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('plans', 'acces_jarvis',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('plans', 'acces_analyse')
    op.drop_column('plans', 'acces_templates')
    op.drop_column('plans', 'acces_recurrentes')
    op.drop_column('plans', 'acces_epargne')
    op.drop_column('plans', 'acces_dettes')
    op.drop_column('plans', 'prix_annuel')
    op.drop_column('plans', 'prix_mensuel')
    op.drop_column('abonnements', 'cycle_facturation')
    # ### end Alembic commands ###
