"""hacher les refresh tokens (token devient token_hash)

Revision ID: 1caf34a024c3
Revises: ce79ad210895
Create Date: 2026-07-31 21:32:40.845438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caf34a024c3'
down_revision: Union[str, Sequence[str], None] = 'ce79ad210895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Les jetons existants sont stockés en clair et ne peuvent pas être
    # transformés en empreinte a posteriori (le hachage n'est pas
    # réversible en sens inverse) — on les purge plutôt qu'ajouter un
    # server_default partagé, qui violerait l'unicité dès la 2e ligne.
    # Conséquence acceptée : toutes les sessions actives sont déconnectées,
    # une seule fois, par cette migration de sécurité.
    op.execute("DELETE FROM refresh_tokens")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
