"""initial schema (utilisateurs, clients, administrateurs, profiles, refresh_tokens)

Revision ID: 23e62b6cb653
Revises: 
Create Date: 2026-07-24 16:41:45.885664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e62b6cb653'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_utilisateur')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id_utilisateur'), 'utilisateurs', ['id_utilisateur'], unique=False)
    op.create_table('administrateurs',
    sa.Column('id_administrateur', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('niveau_acces', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_administrateur')
    )
    op.create_index(op.f('ix_administrateurs_username'), 'administrateurs', ['username'], unique=True)
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('reset_password_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('reset_password_token')
    )
    op.create_index(op.f('ix_clients_username'), 'clients', ['username'], unique=True)
    op.create_table('profiles',
    sa.Column('id_profile', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('langue', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_profile'),
    sa.UniqueConstraint('id_client')
    )
    op.create_index(op.f('ix_profiles_id_profile'), 'profiles', ['id_profile'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id_refresh_token', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('est_revoque', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_refresh_token')
    )
    op.create_index(op.f('ix_refresh_tokens_id_refresh_token'), 'refresh_tokens', ['id_refresh_token'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id_refresh_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profiles_id_profile'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_clients_username'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_administrateurs_username'), table_name='administrateurs')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_utilisateurs_id_utilisateur'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
