"""ajouter otp_code et otp_expiration a utilisateurs pour la double authentification

Revision ID: 23ee034612ed
Revises: 7c89d94b7a26
Create Date: 2026-07-27 13:37:16.028386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ee034612ed'
down_revision: Union[str, Sequence[str], None] = '7c89d94b7a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('utilisateurs', sa.Column('otp_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'otp_expiration')
    op.drop_column('utilisateurs', 'otp_code')
    # ### end Alembic commands ###
