"""rendre id_categorie nullable sur transactions (ecritures systeme)

Revision ID: 28fedfe51a1e
Revises: ea97a10f41f7
Create Date: 2026-07-24 19:31:17.981904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fedfe51a1e'
down_revision: Union[str, Sequence[str], None] = 'ea97a10f41f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'id_categorie',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'id_categorie',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
