"""ajouter est_actif et contrainte unique sur categories

Revision ID: 2ed652a55753
Revises: 92b7c19d0c7c
Create Date: 2026-07-25 14:46:50.392461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed652a55753'
down_revision: Union[str, Sequence[str], None] = '92b7c19d0c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default temporaire pour que les lignes déjà existantes
    # deviennent est_actif=True au lieu de violer le NOT NULL ; retiré
    # juste après, l'application gère le défaut pour les nouvelles lignes.
    op.add_column('categories', sa.Column('est_actif', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('categories', 'est_actif', server_default=None)
    op.create_unique_constraint('uq_categories_client_nom_type', 'categories', ['id_client', 'nom', 'type'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_client_nom_type', 'categories', type_='unique')
    op.drop_column('categories', 'est_actif')
    # ### end Alembic commands ###
