"""ajoute la recharge de compte via mobile money

Revision ID: 3a13f682b6fe
Revises: 7bba7816ca96
Create Date: 2026-08-25 10:29:25.322408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a13f682b6fe'
down_revision: Union[str, Sequence[str], None] = '7bba7816ca96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharges_compte',
    sa.Column('id_recharge', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('reference_hrpay', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte'], ['comptes_financiers.id_compte'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_recharge')
    )
    op.create_index(op.f('ix_recharges_compte_id_client'), 'recharges_compte', ['id_client'], unique=False)
    op.create_index(op.f('ix_recharges_compte_id_compte'), 'recharges_compte', ['id_compte'], unique=False)
    op.create_index(op.f('ix_recharges_compte_id_recharge'), 'recharges_compte', ['id_recharge'], unique=False)
    op.create_index(op.f('ix_recharges_compte_reference_hrpay'), 'recharges_compte', ['reference_hrpay'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_recharges_compte_reference_hrpay'), table_name='recharges_compte')
    op.drop_index(op.f('ix_recharges_compte_id_recharge'), table_name='recharges_compte')
    op.drop_index(op.f('ix_recharges_compte_id_compte'), table_name='recharges_compte')
    op.drop_index(op.f('ix_recharges_compte_id_client'), table_name='recharges_compte')
    op.drop_table('recharges_compte')
    # ### end Alembic commands ###
