"""module dettes : lien transaction-dette et types dette_recue/creance_accordee

Revision ID: 474fd3e86f4c
Revises: f0f47e8e26b2
Create Date: 2026-07-24 20:38:56.981254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474fd3e86f4c'
down_revision: Union[str, Sequence[str], None] = 'f0f47e8e26b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('id_dette', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_id_dette'), 'transactions', ['id_dette'], unique=False)
    op.create_foreign_key('fk_transactions_id_dette', 'transactions', 'dettes', ['id_dette'], ['id_dette'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_id_dette', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id_dette'), table_name='transactions')
    op.drop_column('transactions', 'id_dette')
    # ### end Alembic commands ###
