"""ajouter la table notifications

Revision ID: 6252ba0e5ac2
Revises: 23ee034612ed
Create Date: 2026-07-28 18:24:56.556661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6252ba0e5ac2'
down_revision: Union[str, Sequence[str], None] = '23ee034612ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id_notification', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('destinataire_type', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('lien', sa.String(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    op.create_index(op.f('ix_notifications_date_creation'), 'notifications', ['date_creation'], unique=False)
    op.create_index(op.f('ix_notifications_destinataire_type'), 'notifications', ['destinataire_type'], unique=False)
    op.create_index(op.f('ix_notifications_id_notification'), 'notifications', ['id_notification'], unique=False)
    op.create_index(op.f('ix_notifications_id_utilisateur'), 'notifications', ['id_utilisateur'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id_utilisateur'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id_notification'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_destinataire_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_date_creation'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
