"""ajouter audit_logs et configs (fondation traçabilité)

Revision ID: 64a48a5f4da1
Revises: 8d5d48a2ba23
Create Date: 2026-07-24 18:29:22.675918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a48a5f4da1'
down_revision: Union[str, Sequence[str], None] = '8d5d48a2ba23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(), nullable=False),
    sa.Column('valeur', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.create_index(op.f('ix_configs_cle'), 'configs', ['cle'], unique=True)
    op.create_index(op.f('ix_configs_id_config'), 'configs', ['id_config'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id_audit', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ressource', sa.String(), nullable=False),
    sa.Column('id_ressource', sa.Integer(), nullable=True),
    sa.Column('donnees_avant', sa.JSON(), nullable=True),
    sa.Column('donnees_apres', sa.JSON(), nullable=True),
    sa.Column('adresse_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_audit')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_date_creation'), 'audit_logs', ['date_creation'], unique=False)
    op.create_index(op.f('ix_audit_logs_id_audit'), 'audit_logs', ['id_audit'], unique=False)
    op.create_index(op.f('ix_audit_logs_id_utilisateur'), 'audit_logs', ['id_utilisateur'], unique=False)
    op.create_index(op.f('ix_audit_logs_ressource'), 'audit_logs', ['ressource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_ressource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id_utilisateur'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id_audit'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_date_creation'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_configs_id_config'), table_name='configs')
    op.drop_index(op.f('ix_configs_cle'), table_name='configs')
    op.drop_table('configs')
    # ### end Alembic commands ###
