"""supprimer la table webhook_events (module webhooks mort, jamais utilise)

Revision ID: 7c89d94b7a26
Revises: 44ba0347804a
Create Date: 2026-07-27 10:30:21.259368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c89d94b7a26'
down_revision: Union[str, Sequence[str], None] = '44ba0347804a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_id_client'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id_webhook'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id_webhook', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_client', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_event', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nombre_tentatives', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_prochain_essai', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], name=op.f('webhook_events_id_client_fkey')),
    sa.PrimaryKeyConstraint('id_webhook', name=op.f('webhook_events_pkey'))
    )
    op.create_index(op.f('ix_webhook_events_id_webhook'), 'webhook_events', ['id_webhook'], unique=False)
    op.create_index(op.f('ix_webhook_events_id_client'), 'webhook_events', ['id_client'], unique=False)
    # ### end Alembic commands ###
