"""supprimer la colonne username de clients

Revision ID: 8d5d48a2ba23
Revises: 23e62b6cb653
Create Date: 2026-07-24 18:07:00.397476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5d48a2ba23'
down_revision: Union[str, Sequence[str], None] = '23e62b6cb653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_username'), table_name='clients')
    op.drop_column('clients', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_clients_username'), 'clients', ['username'], unique=True)
    # ### end Alembic commands ###
