"""budgets: soft delete et contrainte unique client-categorie-mois-annee

Revision ID: 92b7c19d0c7c
Revises: 474fd3e86f4c
Create Date: 2026-07-24 21:23:54.470017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b7c19d0c7c'
down_revision: Union[str, Sequence[str], None] = '474fd3e86f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('est_actif', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uq_budgets_client_categorie_mois_annee', 'budgets', ['id_client', 'id_categorie', 'mois', 'annee'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_budgets_client_categorie_mois_annee', 'budgets', type_='unique')
    op.drop_column('budgets', 'est_actif')
    # ### end Alembic commands ###
