"""ajouter le module tontines et acces_tontine sur plans

Revision ID: c2757cd1d426
Revises: d400bd159c0c
Create Date: 2026-08-11 19:52:00.786154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2757cd1d426'
down_revision: Union[str, Sequence[str], None] = 'd400bd159c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tontines',
    sa.Column('id_tontine', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('montant_cotisation', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('frequence', sa.String(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_tontine')
    )
    op.create_index(op.f('ix_tontines_id_client'), 'tontines', ['id_client'], unique=False)
    op.create_index(op.f('ix_tontines_id_tontine'), 'tontines', ['id_tontine'], unique=False)
    op.create_table('membres_tontine',
    sa.Column('id_membre', sa.Integer(), nullable=False),
    sa.Column('id_tontine', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tontine'], ['tontines.id_tontine'], ),
    sa.PrimaryKeyConstraint('id_membre')
    )
    op.create_index(op.f('ix_membres_tontine_id_membre'), 'membres_tontine', ['id_membre'], unique=False)
    op.create_index(op.f('ix_membres_tontine_id_tontine'), 'membres_tontine', ['id_tontine'], unique=False)
    op.create_table('tours_tontine',
    sa.Column('id_tour', sa.Integer(), nullable=False),
    sa.Column('id_tontine', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('id_membre_beneficiaire', sa.Integer(), nullable=False),
    sa.Column('date_prevue', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_membre_beneficiaire'], ['membres_tontine.id_membre'], ),
    sa.ForeignKeyConstraint(['id_tontine'], ['tontines.id_tontine'], ),
    sa.PrimaryKeyConstraint('id_tour')
    )
    op.create_index(op.f('ix_tours_tontine_id_tontine'), 'tours_tontine', ['id_tontine'], unique=False)
    op.create_index(op.f('ix_tours_tontine_id_tour'), 'tours_tontine', ['id_tour'], unique=False)
    op.create_table('cotisations_tour',
    sa.Column('id_cotisation', sa.Integer(), nullable=False),
    sa.Column('id_tour', sa.Integer(), nullable=False),
    sa.Column('id_membre', sa.Integer(), nullable=False),
    sa.Column('est_versee', sa.Boolean(), nullable=False),
    sa.Column('date_versement', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_membre'], ['membres_tontine.id_membre'], ),
    sa.ForeignKeyConstraint(['id_tour'], ['tours_tontine.id_tour'], ),
    sa.PrimaryKeyConstraint('id_cotisation')
    )
    op.create_index(op.f('ix_cotisations_tour_id_cotisation'), 'cotisations_tour', ['id_cotisation'], unique=False)
    op.create_index(op.f('ix_cotisations_tour_id_membre'), 'cotisations_tour', ['id_membre'], unique=False)
    op.create_index(op.f('ix_cotisations_tour_id_tour'), 'cotisations_tour', ['id_tour'], unique=False)
    op.add_column('plans', sa.Column('acces_tontine', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # Même palier que Dettes/Épargne (voir Plan.acces_tontine) : la tontine
    # est conceptuellement une fusion des deux (cotisations tournantes +
    # objectif collectif).
    op.execute("UPDATE plans SET acces_tontine = true WHERE nom IN ('ESSENTIEL', 'PREMIUM')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'acces_tontine')
    op.drop_index(op.f('ix_cotisations_tour_id_tour'), table_name='cotisations_tour')
    op.drop_index(op.f('ix_cotisations_tour_id_membre'), table_name='cotisations_tour')
    op.drop_index(op.f('ix_cotisations_tour_id_cotisation'), table_name='cotisations_tour')
    op.drop_table('cotisations_tour')
    op.drop_index(op.f('ix_tours_tontine_id_tour'), table_name='tours_tontine')
    op.drop_index(op.f('ix_tours_tontine_id_tontine'), table_name='tours_tontine')
    op.drop_table('tours_tontine')
    op.drop_index(op.f('ix_membres_tontine_id_tontine'), table_name='membres_tontine')
    op.drop_index(op.f('ix_membres_tontine_id_membre'), table_name='membres_tontine')
    op.drop_table('membres_tontine')
    op.drop_index(op.f('ix_tontines_id_tontine'), table_name='tontines')
    op.drop_index(op.f('ix_tontines_id_client'), table_name='tontines')
    op.drop_table('tontines')
    # ### end Alembic commands ###
