"""ajouter transactions recurrentes et templates (date_fin, id_transaction_recurrente, est_actif)

Revision ID: ccafcc510ebc
Revises: 2ed652a55753
Create Date: 2026-07-25 15:13:24.296777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccafcc510ebc'
down_revision: Union[str, Sequence[str], None] = '2ed652a55753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default temporaire pour que les lignes déjà existantes
    # deviennent est_actif=True au lieu de violer le NOT NULL ; retiré
    # juste après, l'application gère le défaut pour les nouvelles lignes.
    op.add_column('templates_transaction', sa.Column('est_actif', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('templates_transaction', 'est_actif', server_default=None)
    op.add_column('transactions', sa.Column('id_transaction_recurrente', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_id_transaction_recurrente'), 'transactions', ['id_transaction_recurrente'], unique=False)
    op.create_foreign_key('fk_transactions_id_transaction_recurrente', 'transactions', 'transactions_recurrentes', ['id_transaction_recurrente'], ['id_transaction_recurrente'])
    op.add_column('transactions_recurrentes', sa.Column('date_fin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions_recurrentes', 'date_fin')
    op.drop_constraint('fk_transactions_id_transaction_recurrente', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id_transaction_recurrente'), table_name='transactions')
    op.drop_column('transactions', 'id_transaction_recurrente')
    op.drop_column('templates_transaction', 'est_actif')
    # ### end Alembic commands ###
