"""ajouter le suivi des tentatives de connexion echouees

Revision ID: ce79ad210895
Revises: 6252ba0e5ac2
Create Date: 2026-07-30 22:50:25.121572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce79ad210895'
down_revision: Union[str, Sequence[str], None] = '6252ba0e5ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust ###
    # server_default requis : colonnes NOT NULL ajoutées sur une table déjà
    # peuplée (autogenerate ne le déduit jamais du default= Python de l'ORM,
    # qui ne s'applique qu'aux futurs INSERT).
    op.add_column('utilisateurs', sa.Column('tentatives_echouees', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('utilisateurs', sa.Column('alerte_tentatives_envoyee', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'alerte_tentatives_envoyee')
    op.drop_column('utilisateurs', 'tentatives_echouees')
    # ### end Alembic commands ###
