"""ajouter options_suggerees et necessite_clarification, corriger montant_suggere en Numeric sur messages

Revision ID: d139ca69343f
Revises: ccafcc510ebc
Create Date: 2026-07-25 15:54:54.073238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd139ca69343f'
down_revision: Union[str, Sequence[str], None] = 'ccafcc510ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default temporaire pour que les lignes déjà existantes
    # deviennent necessite_clarification=False au lieu de violer le
    # NOT NULL ; retiré juste après.
    op.add_column('messages', sa.Column('necessite_clarification', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('messages', 'necessite_clarification', server_default=None)
    op.add_column('messages', sa.Column('options_suggerees', sa.JSON(), nullable=True))
    op.alter_column('messages', 'montant_suggere',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'montant_suggere',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('messages', 'options_suggerees')
    op.drop_column('messages', 'necessite_clarification')
    # ### end Alembic commands ###
