"""ajouter est_actif sur dettes pour suppression logique

Revision ID: d400bd159c0c
Revises: 1caf34a024c3
Create Date: 2026-08-09 15:14:16.087960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd400bd159c0c'
down_revision: Union[str, Sequence[str], None] = '1caf34a024c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dettes', sa.Column('est_actif', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dettes', 'est_actif')
    # ### end Alembic commands ###
