"""ajouter les 27 classes du cahier des charges (comptes, transactions, budgets, epargne, dettes, rapports, jarvis, analyse, plans, webhooks)

Revision ID: ea97a10f41f7
Revises: 64a48a5f4da1
Create Date: 2026-07-24 19:07:01.911233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea97a10f41f7'
down_revision: Union[str, Sequence[str], None] = '64a48a5f4da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('max_comptes', sa.Integer(), nullable=False),
    sa.Column('max_transactions', sa.Integer(), nullable=False),
    sa.Column('acces_jarvis', sa.Boolean(), nullable=True),
    sa.Column('acces_prediction', sa.Boolean(), nullable=True),
    sa.Column('acces_rapport', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_plan'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_plans_id_plan'), 'plans', ['id_plan'], unique=False)
    op.create_table('abonnements',
    sa.Column('id_abonnement', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('renouvellement_auto', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plans.id_plan'], ),
    sa.PrimaryKeyConstraint('id_abonnement'),
    sa.UniqueConstraint('id_client')
    )
    op.create_index(op.f('ix_abonnements_id_abonnement'), 'abonnements', ['id_abonnement'], unique=False)
    op.create_table('analyses_financieres',
    sa.Column('id_analyse', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('resultats', sa.JSON(), nullable=True),
    sa.Column('score_financier', sa.Float(), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_analyse')
    )
    op.create_index(op.f('ix_analyses_financieres_id_analyse'), 'analyses_financieres', ['id_analyse'], unique=False)
    op.create_index(op.f('ix_analyses_financieres_id_client'), 'analyses_financieres', ['id_client'], unique=False)
    op.create_table('categories',
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('icone', sa.String(), nullable=True),
    sa.Column('couleur', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_categorie')
    )
    op.create_index(op.f('ix_categories_id_categorie'), 'categories', ['id_categorie'], unique=False)
    op.create_index(op.f('ix_categories_id_client'), 'categories', ['id_client'], unique=False)
    op.create_table('comptes_financiers',
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('solde', sa.Float(), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_compte')
    )
    op.create_index(op.f('ix_comptes_financiers_id_client'), 'comptes_financiers', ['id_client'], unique=False)
    op.create_index(op.f('ix_comptes_financiers_id_compte'), 'comptes_financiers', ['id_compte'], unique=False)
    op.create_table('comptes_principaux',
    sa.Column('id_compte_principal', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('solde_total', sa.Float(), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('date_mise_a_jour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_compte_principal'),
    sa.UniqueConstraint('id_client')
    )
    op.create_index(op.f('ix_comptes_principaux_id_compte_principal'), 'comptes_principaux', ['id_compte_principal'], unique=False)
    op.create_table('conversations',
    sa.Column('id_conversation', sa.Uuid(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_dernier_message', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_conversation')
    )
    op.create_index(op.f('ix_conversations_id_client'), 'conversations', ['id_client'], unique=False)
    op.create_table('predictions',
    sa.Column('id_prediction', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('montant_predit', sa.Float(), nullable=True),
    sa.Column('niveau_confiance', sa.Float(), nullable=True),
    sa.Column('recommandations', sa.String(), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_prediction')
    )
    op.create_index(op.f('ix_predictions_id_client'), 'predictions', ['id_client'], unique=False)
    op.create_index(op.f('ix_predictions_id_prediction'), 'predictions', ['id_prediction'], unique=False)
    op.create_table('rapports',
    sa.Column('id_rapport', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=False),
    sa.Column('periode_fin', sa.Date(), nullable=False),
    sa.Column('chemin_fichier', sa.String(), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    op.create_index(op.f('ix_rapports_id_client'), 'rapports', ['id_client'], unique=False)
    op.create_index(op.f('ix_rapports_id_rapport'), 'rapports', ['id_rapport'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id_webhook', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('type_event', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('nombre_tentatives', sa.Integer(), nullable=True),
    sa.Column('date_prochain_essai', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_webhook')
    )
    op.create_index(op.f('ix_webhook_events_id_client'), 'webhook_events', ['id_client'], unique=False)
    op.create_index(op.f('ix_webhook_events_id_webhook'), 'webhook_events', ['id_webhook'], unique=False)
    op.create_table('budgets',
    sa.Column('id_budget', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('montant_limite', sa.Float(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('alerte_80', sa.Boolean(), nullable=True),
    sa.Column('alerte_100', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id_categorie'], ),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_budget')
    )
    op.create_index(op.f('ix_budgets_id_budget'), 'budgets', ['id_budget'], unique=False)
    op.create_index(op.f('ix_budgets_id_client'), 'budgets', ['id_client'], unique=False)
    op.create_table('messages',
    sa.Column('id_message', sa.Uuid(), nullable=False),
    sa.Column('id_conversation', sa.Uuid(), nullable=False),
    sa.Column('contenu', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('peut_se_permettre', sa.Boolean(), nullable=True),
    sa.Column('montant_suggere', sa.Float(), nullable=True),
    sa.Column('conseil_supplementaire', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conversation'], ['conversations.id_conversation'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_index(op.f('ix_messages_id_conversation'), 'messages', ['id_conversation'], unique=False)
    op.create_table('objectifs_epargne',
    sa.Column('id_objectif', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte_epargne', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('montant_cible', sa.Float(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte_epargne'], ['comptes_financiers.id_compte'], ),
    sa.PrimaryKeyConstraint('id_objectif'),
    sa.UniqueConstraint('id_compte_epargne')
    )
    op.create_index(op.f('ix_objectifs_epargne_id_client'), 'objectifs_epargne', ['id_client'], unique=False)
    op.create_index(op.f('ix_objectifs_epargne_id_objectif'), 'objectifs_epargne', ['id_objectif'], unique=False)
    op.create_table('templates_transaction',
    sa.Column('id_template', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('nombre_utilisations', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id_categorie'], ),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte'], ['comptes_financiers.id_compte'], ),
    sa.PrimaryKeyConstraint('id_template')
    )
    op.create_index(op.f('ix_templates_transaction_id_client'), 'templates_transaction', ['id_client'], unique=False)
    op.create_index(op.f('ix_templates_transaction_id_template'), 'templates_transaction', ['id_template'], unique=False)
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('est_recurrente', sa.Boolean(), nullable=True),
    sa.Column('est_suspecte', sa.Boolean(), nullable=True),
    sa.Column('id_transaction_annulee', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id_categorie'], ),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte'], ['comptes_financiers.id_compte'], ),
    sa.ForeignKeyConstraint(['id_transaction_annulee'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_index(op.f('ix_transactions_id_categorie'), 'transactions', ['id_categorie'], unique=False)
    op.create_index(op.f('ix_transactions_id_client'), 'transactions', ['id_client'], unique=False)
    op.create_index(op.f('ix_transactions_id_compte'), 'transactions', ['id_compte'], unique=False)
    op.create_index(op.f('ix_transactions_id_transaction'), 'transactions', ['id_transaction'], unique=False)
    op.create_table('transactions_recurrentes',
    sa.Column('id_transaction_recurrente', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('frequence', sa.String(), nullable=False),
    sa.Column('prochaine_execution', sa.Date(), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id_categorie'], ),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte'], ['comptes_financiers.id_compte'], ),
    sa.PrimaryKeyConstraint('id_transaction_recurrente')
    )
    op.create_index(op.f('ix_transactions_recurrentes_id_client'), 'transactions_recurrentes', ['id_client'], unique=False)
    op.create_index(op.f('ix_transactions_recurrentes_id_transaction_recurrente'), 'transactions_recurrentes', ['id_transaction_recurrente'], unique=False)
    op.create_table('transferts',
    sa.Column('id_transfert', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_compte_source', sa.Integer(), nullable=False),
    sa.Column('id_compte_destination', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte_destination'], ['comptes_financiers.id_compte'], ),
    sa.ForeignKeyConstraint(['id_compte_source'], ['comptes_financiers.id_compte'], ),
    sa.PrimaryKeyConstraint('id_transfert')
    )
    op.create_index(op.f('ix_transferts_id_client'), 'transferts', ['id_client'], unique=False)
    op.create_index(op.f('ix_transferts_id_transfert'), 'transferts', ['id_transfert'], unique=False)
    op.create_table('actions_ia',
    sa.Column('id_action', sa.Uuid(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_message', sa.Uuid(), nullable=False),
    sa.Column('type_action', sa.String(), nullable=False),
    sa.Column('donnees_cible', sa.String(), nullable=True),
    sa.Column('confirmation_token', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_expiration', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_message'], ['messages.id_message'], ),
    sa.PrimaryKeyConstraint('id_action'),
    sa.UniqueConstraint('confirmation_token')
    )
    op.create_index(op.f('ix_actions_ia_id_client'), 'actions_ia', ['id_client'], unique=False)
    op.create_table('dettes',
    sa.Column('id_dette', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_transaction_origine', sa.Integer(), nullable=True),
    sa.Column('id_compte', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('montant_total', sa.Float(), nullable=False),
    sa.Column('montant_rembourse', sa.Float(), nullable=False),
    sa.Column('personne_impliquee', sa.String(), nullable=True),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_compte'], ['comptes_financiers.id_compte'], ),
    sa.ForeignKeyConstraint(['id_transaction_origine'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_dette')
    )
    op.create_index(op.f('ix_dettes_id_client'), 'dettes', ['id_client'], unique=False)
    op.create_index(op.f('ix_dettes_id_dette'), 'dettes', ['id_dette'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dettes_id_dette'), table_name='dettes')
    op.drop_index(op.f('ix_dettes_id_client'), table_name='dettes')
    op.drop_table('dettes')
    op.drop_index(op.f('ix_actions_ia_id_client'), table_name='actions_ia')
    op.drop_table('actions_ia')
    op.drop_index(op.f('ix_transferts_id_transfert'), table_name='transferts')
    op.drop_index(op.f('ix_transferts_id_client'), table_name='transferts')
    op.drop_table('transferts')
    op.drop_index(op.f('ix_transactions_recurrentes_id_transaction_recurrente'), table_name='transactions_recurrentes')
    op.drop_index(op.f('ix_transactions_recurrentes_id_client'), table_name='transactions_recurrentes')
    op.drop_table('transactions_recurrentes')
    op.drop_index(op.f('ix_transactions_id_transaction'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id_compte'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id_client'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id_categorie'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_templates_transaction_id_template'), table_name='templates_transaction')
    op.drop_index(op.f('ix_templates_transaction_id_client'), table_name='templates_transaction')
    op.drop_table('templates_transaction')
    op.drop_index(op.f('ix_objectifs_epargne_id_objectif'), table_name='objectifs_epargne')
    op.drop_index(op.f('ix_objectifs_epargne_id_client'), table_name='objectifs_epargne')
    op.drop_table('objectifs_epargne')
    op.drop_index(op.f('ix_messages_id_conversation'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_budgets_id_client'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id_budget'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_webhook_events_id_webhook'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id_client'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_rapports_id_rapport'), table_name='rapports')
    op.drop_index(op.f('ix_rapports_id_client'), table_name='rapports')
    op.drop_table('rapports')
    op.drop_index(op.f('ix_predictions_id_prediction'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id_client'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_conversations_id_client'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_comptes_principaux_id_compte_principal'), table_name='comptes_principaux')
    op.drop_table('comptes_principaux')
    op.drop_index(op.f('ix_comptes_financiers_id_compte'), table_name='comptes_financiers')
    op.drop_index(op.f('ix_comptes_financiers_id_client'), table_name='comptes_financiers')
    op.drop_table('comptes_financiers')
    op.drop_index(op.f('ix_categories_id_client'), table_name='categories')
    op.drop_index(op.f('ix_categories_id_categorie'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_analyses_financieres_id_client'), table_name='analyses_financieres')
    op.drop_index(op.f('ix_analyses_financieres_id_analyse'), table_name='analyses_financieres')
    op.drop_table('analyses_financieres')
    op.drop_index(op.f('ix_abonnements_id_abonnement'), table_name='abonnements')
    op.drop_table('abonnements')
    op.drop_index(op.f('ix_plans_id_plan'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
