"""ajouter la table paiements_abonnement (HR-Skills Pay)

Revision ID: ecac5edb6613
Revises: 0513c3e2bc26
Create Date: 2026-07-25 18:21:42.586770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecac5edb6613'
down_revision: Union[str, Sequence[str], None] = '0513c3e2bc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements_abonnement',
    sa.Column('id_paiement', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_plan_demande', sa.Integer(), nullable=False),
    sa.Column('cycle_facturation', sa.String(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('devise', sa.String(), nullable=False),
    sa.Column('reference_hrpay', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_confirmation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_plan_demande'], ['plans.id_plan'], ),
    sa.PrimaryKeyConstraint('id_paiement')
    )
    op.create_index(op.f('ix_paiements_abonnement_id_client'), 'paiements_abonnement', ['id_client'], unique=False)
    op.create_index(op.f('ix_paiements_abonnement_id_paiement'), 'paiements_abonnement', ['id_paiement'], unique=False)
    op.create_index(op.f('ix_paiements_abonnement_reference_hrpay'), 'paiements_abonnement', ['reference_hrpay'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_abonnement_reference_hrpay'), table_name='paiements_abonnement')
    op.drop_index(op.f('ix_paiements_abonnement_id_paiement'), table_name='paiements_abonnement')
    op.drop_index(op.f('ix_paiements_abonnement_id_client'), table_name='paiements_abonnement')
    op.drop_table('paiements_abonnement')
    # ### end Alembic commands ###
