"""ajoute email_verifie sur utilisateurs

Revision ID: eeaddd66920f
Revises: c2757cd1d426
Create Date: 2026-08-17 15:59:03.034884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeaddd66920f'
down_revision: Union[str, Sequence[str], None] = 'c2757cd1d426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default temporaire pour que les lignes déjà existantes reçoivent
    # False sans violer la contrainte NOT NULL, retiré juste après (même
    # principe que 2ed652a55753) — le modèle ORM reste la seule source de
    # vérité du défaut pour les futures insertions.
    op.add_column('utilisateurs', sa.Column('email_verifie', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('utilisateurs', 'email_verifie', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'email_verifie')
    # ### end Alembic commands ###
