"""numeric pour les montants, contraintes CHECK solde/montant, verrouillage

Revision ID: f0f47e8e26b2
Revises: 28fedfe51a1e
Create Date: 2026-07-24 20:08:18.958998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f47e8e26b2'
down_revision: Union[str, Sequence[str], None] = '28fedfe51a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'montant_limite',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('comptes_financiers', 'solde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('comptes_principaux', 'solde_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('dettes', 'montant_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('dettes', 'montant_rembourse',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('objectifs_epargne', 'montant_cible',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('plans', 'prix',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('predictions', 'montant_predit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('templates_transaction', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('transactions_recurrentes', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('transferts', 'montant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Contraintes CHECK ajoutées manuellement : non détectées par
    # l'autogenerate d'Alembic (limitation connue pour les CheckConstraint).
    op.create_check_constraint(
        "ck_comptes_financiers_solde_non_negatif", "comptes_financiers", "solde >= 0"
    )
    op.create_check_constraint(
        "ck_transactions_montant_positif", "transactions", "montant > 0"
    )
    op.create_check_constraint(
        "ck_transferts_montant_positif", "transferts", "montant > 0"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_transferts_montant_positif", "transferts", type_="check")
    op.drop_constraint("ck_transactions_montant_positif", "transactions", type_="check")
    op.drop_constraint("ck_comptes_financiers_solde_non_negatif", "comptes_financiers", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transferts', 'montant',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions_recurrentes', 'montant',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'montant',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('templates_transaction', 'montant',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('predictions', 'montant_predit',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('plans', 'prix',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('objectifs_epargne', 'montant_cible',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('dettes', 'montant_rembourse',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('dettes', 'montant_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('comptes_principaux', 'solde_total',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('comptes_financiers', 'solde',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('budgets', 'montant_limite',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
